### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by vewaclub** [plasmoapp/matter#9]
Сервер перестаёт отвечать через минут 30 игры

Лог краша: https://pastebin.com/M7uTSHEa
Плагины 
![изображение](https://user-images.githubusercontent.com/72296110/178007546-a23c7711-9c49-472e-80dd-da6400680d7f.png)
Версия майнкрафт: 1.19
Онлайн: 6

**Comment by erxson** [comment]
Что за панелька такая красивая? @IQPILLS

**Comment by vewaclub** [comment]
coralhost @erxson
